### ISSUE TITLE
The starter sets the `font-family` of `code` and `pre` to a CSS var that may not be generated

### ISSUE THREAD

**Issue by michaellenaghan** [ThinkUniform/uniformcss#34]
This:

```scss
pre, code {
    font-family: var(--font-mono);
}
```

is [here](https://github.com/ThinkUniform/uniformcss/blob/6a4aee9806a0aa2125dcea2b247f8c427ce2cd71/uniform/core/starter/_index.scss#L41). But if `css-variables` is configured to `false` CSS vars aren't generated.
